services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
    ports:
      - "5433:5432"

  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=testing
      - DATABASE_URL=postgresql://test_user:test_password@db:5432/test_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3001:3000"
    environment:
      - VITE_API_URL=http://localhost:5001/api
    depends_on:
      - backend