services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: myapp_db
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: 
      context: .
      dockerfile: docker/Dockerfile.dev
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app/backend
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://myapp_user:myapp_password@db:5432/myapp_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:5000/api

volumes:
  postgres_data: